#!/bin/bash

source ./webapp.conf

create_ps_db(){
  SECUREPASS=`tr -dc A-Za-z0-9 < /dev/urandom | head -c 20 | xargs`
  echo "Создаем пользователя $PROJECTDIR c паролем $SECUREPASS и базу $PROJECTDIR"
  sudo -u postgres createuser -U $PROJECTDIR -W $SECUREPASS
  sudo -u postgres createdb --owner $PROJECTDIR $UNIXUSERNAME
}

comlete_task(){
  echo -e "Subject: Был создан проект $PROJECTDIR\n\
  Был создан проект со следующими параметрами: \n\
  Директория проекта: /$ROOTDIR/$PROJECTDIR/$PROJECTNAME \n\
  Директория virtualenv окружения: /$ROOTDIR/$PROJECTDIR \n\
  Директория файлов журнала: /$ROOTDIR/$PROJECTDIR/logs \n\
  Файл конфигурации nginx: /etc/nginx/site-available/$PROJECTNAME \n\
  Файл конфигурации supervisor: /etc/supervisor/conf.d/${PROJECTNAME}.conf \n\
  Файл запуска Gunicorn: /$ROOTDIR/$PROJECTDIR/bin/gunicorn_start \n\
  Название проекта: $PROJECTNAME и $PROJECTDIR \n\
  Доменное имя сайта: $SITENAME и переадресация с www.$SITENAME \n\
  \n\
  Необходимо создать или перенести само Django-приложение \n\
  Незабудьте выполнить sudo supervisorctl update и sudo service nginx reload \n\
  а также добавить Gunicorn в список зависимостей или установить его отдельно в virtualenv \n"\
  > /$ROOTDIR/$PROJECTDIR/README.txt

  if [ "$PSCREATE" = "y" ]; then
    echo -e "\nТакже была создана база данных PostreSQL $PROJECTNAME \n\
    Имя пользователя: $PROJECTDIR\n\
    Пароль: $SECUREPASS"\
    > /$ROOTDIR/$PROJECTDIR/README.txt
  fi
  
  cat /$ROOTDIR/$PROJECTDIR/README.txt | sendmail $MAILTO
}

create_config(){
  cat $1 | \
  sed -e s/PROJECTNAME/${PROJECTNAME}/g   | \
  sed -e s/PROJECTDIR/${PROJECTDIR}/g     | \
  sed -e s/UNIXUSERNAME/${UNIXUSERNAME}/g | \
  sed -e s/SITENAME/${SITENAME}/g         > $2
  echo -e "Записан файл $2"
}

create_new_django_project(){
  echo -e "Создаем пользователя $UNIXUSERNAME с домашней директорией /$ROOTDIR/$PROJECTDIR"
  useradd --system --gid $ROOTDIR --shell /bin/bash --home /$ROOTDIR/$PROJECTDIR $UNIXUSERNAME
  echo -e "Создаем директорию приложения /$ROOTDIR/$PROJECTDIR"
  mkdir -p /$ROOTDIR/$PROJECTDIR/bin
  mkdir -p /$ROOTDIR/$PROJECTDIR/logs
  touch /$ROOTDIR/$PROJECTDIR/logs/gunicorn_supervisor.log

  echo -e "Создаем файлы конфигурации Nginx, Gunicorn и Supervisor из шаблонов"
  create_config "./configs/nginx-vhost-config" "/etc/nginx/sites-available/$PROJECTNAME"
  create_config "./configs/gunicorn_start" "/$ROOTDIR/$PROJECTDIR/bin/gunicorn_start"
  create_config "./configs/supervisor.conf" "/etc/supervisor/conf.d/${PROJECTNAME}.conf"

  supervisorctl reread
  ln -s /etc/nginx/sites-available/$PROJECTNAME /etc/nginx/sites-enabled/$PROJECTNAME
  chmod u+x /$ROOTDIR/$PROJECTDIR/bin/gunicorn_start 

  echo -e "Назначаем ${UNIXUSERNAME}:users владельцем /$ROOTDIR/$PROJECTDIR"
  chown -R ${UNIXUSERNAME}:users /$ROOTDIR/$PROJECTDIR/
  echo -e "Применяем chmod -R g+w к /$ROOTDIR/$PROJECTDIR"
  chmod -R g+w /$ROOTDIR/$PROJECTDIR

  echo -e "Создаем virtualenv"
  sudo -u $UNIXUSERNAME virtualenv /$ROOTDIR/$PROJECTDIR
  
  echo -e "Создать базу данных PostreSQL (y/[n])?"
  read PSCREATE
  [ "$PSCREATE" = "y" ] && create_ps_db

  complete_task
}

get_settings_for_new_django_project(){
  while [ "$APPROVE" != "y" ]; do
    while [ "$PROJECTNAME" = "" ]; do
      echo "Введите имя проекта (например myproject): "
      read PROJECTNAME
      [ "$PROJECTNAME" = "" ] && echo "Имя проекта не может быть пустым."
    done
    PROJECTDIR="${PROJECTNAME}_django"

    UNIXUSERNAME=""
    echo "Введите имя пользователя для запуска приложения (можно оставить пустым, если совпадает с именем проекта): "
    read UNIXUSERNAME
    [ "$UNIXUSERNAME" = "" ] && UNIXUSERNAME=$PROJECTNAME

    while [ "$SITENAME" = "" ]; do
      echo "Полное доменное имя сайта (например lp.example.pro): "
      read SITENAME
      [ "$SITENAME" = "" ] && echo "Доменное имя не может быть пустым."
    done

    echo -e "Будет создан проект со следующими параметрами: \n\
    Название проекта: $PROJECTNAME \n\
    Имя пользователя: $UNIXUSERNAME \n\
    Доменные имена: $SITENAME и www.$SITENAME \n\
    Рабочий каталог: /$ROOTDIR/$PROJECTDIR \n\
    Каталог журналов: /$ROOTDIR/$PROJECTDIR/logs \n\
    Каталог с файлами Django: /$ROOTDIR/$PROJECTDIR/$PROJECTNAME \n\
    \n Информация верна? (y/[n]/a)"
    read APPROVE
    [ "$APPROVE" = "a" ] && exit 1
  done

  create_new_django_project
}

if [[ $EUID -ne 0 ]]; then
  echo "Скрипт необходимо запускать с правами суперпользователя!"
  exit 1
else
  case "$1" in
    remove)
      echo "Удаляйте вручную :3"
    ;;
    *)
      echo "Создаем новый проект на Django? (y/[a])"
      read ANSWER
      if [ "$ANSWER" = "y" ]; then
        get_settings_for_new_django_project
      else exit 1
      fi
    ;;
  esac
fi
